project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Changing Permafrost Landscapes: Properties, Processes, and Change (ESPM 3000) Syllabus - Fall 2024"
  author: "Nic Jelinski and Katrina Nelson"
  date: "22AUG2024"
  cover-image: "espm-3000.png"
  number: "0.2"
  #navbar: 
    #right: 
      #- icon: cc-circle
      #- href: https://creativecommons.org/licenses/by/4.0/
      #- aria-label: Creative Commons
  
  chapters:
    - index.qmd
    - intro.qmd
    #- course-resources.qmd
    - assignments-points-grades.qmd
    #- poll-everywhere.qmd
    - makeup-policies.qmd
    - ai-policy.qmd
    - fine-print.qmd
    - class-schedule.qmd
    - further-opportunities.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

