# Course Resources

## Required Materials

*Peer-Reviewed Papers (Required)*: 

All of the peer-reviewed papers that you need to access for this course will be available through Canvas. You will need to access these papers to complete your weekly [**Assigned Paper Summary Worksheet**]{#sec-assignments). Note that each week there will be 6 papers posted - you are only responsible for one - the one that matches your assigned letter (A, B, C, D, E or F). Your assigned letter will stay the same for the entire semester. You are free to read and interact with the other papers as you wish, but you are not responsible for them.

## Companion Materials

*Podcasts*: 

This course has a podcast associated with it called "ESPM 3000". The best way to access podcast episodes is through Spotify: [ESPM 3000 on Spotify](https://open.spotify.com/show/2SrwgiszVVgM1dCDWD9xFc?si=a0e58d7ee7e842a9).

*Companion Readings and Deep Dive Materials*: 

Occasionally, we may also post companion readings or deep dive materials that are not required but may be of interest to you. These will be posted on a separate "Deep Dive (Optional)" section of the weekly pages on the Canvas site.

::: callout-tip
## Canvas Access

-   Via myU portal: Go to myU Portal page at <http://myu.umn.edu>, login with your Internet ID, and click on the Key Links tab. Click on Canvas in the dropdown menu.

-   Via Canvas server: Go to <http://canvas.umn.edu> and login there with your Internet ID. Once logged in, you will be able to see the link to sites you have access to.
:::

## Recommended Habits for Success in this Class

Participation is key in this course! There is a regular "rhythm" to every week of the class, and engagement with your peers is key. During a typical week, you will need to complete the [**Assigned Paper Summary**]{#sec-assignments) for your assigned paper, due on Canvas by Thursday at 11:59PM,. You will then complete the weekly [**Group Jigsaw Worksheet**]{#sec-assignments) during the class period on Fridays. Finally, the a [**Synthesis Product**]{#sec-assignments) (either summary figure or critique of an article from a popular news source) will be due prior to class in our final class period (December 6th). You will share your synthesis product in jigsaw fashion with the rest of your small group members.

Course materials will be posted at least one week in advance, so you are free to work on a schedule that works best for you. If you take the time to engage with your assigned paper each week, and attend class, you will be very familiar with the material and should be highly successful in the class.

Come to class prepared to share and participate! We really look forward to meeting and working with you.

**You are encouraged to ask any and all questions - even the "stupid" ones! (P.S. There are no stupid questions ;).**
