# Ways to Get Involved with the Permafrost Community

## Professional Organizations and Mailing Lists

*United States Permafrost Association*: For \$15/year, you can be a student member of the [U.S. Permafrost Association (USPA)](https://www.uspermafrost.org). This provides you access to the quarterly "Frozen Ground Bulletin", USPA exclusive webinars, and the opportunity to apply for travel grants and attend conferences. The USPA is a great way to get involved in the permafrost community, network with permafrost researchers, and stay up to date on the latest information and events.

*Subscribe to the International Permafrost Association (IPA) Mailing List* The mission of the International Permafrost Association (IPA) is to promote research in permafrost and permafrost-related fields within the global scientific and engineering communities, to support the activities of researchers in these disciplines, and to disseminate findings concerning permafrost to the decision-makers, the general public and educators. The IPA maintains a mailing list that you can [sign up for for free](https://www.permafrost.org/mailing-list/). This mailing list sends out information about permafrost conferences, webinars, job opportunities, graduate school positions related to permafrost, and other related issues. The [IPA website](https://www.permafrost.org) also maintains a rich array of resources and reports.

*Subscribe to the Cryolist Mailing List* CRYOLIST is an email mailing list for the global cryospheric community (snow, ice, glaciers, permafrost, ocean, geomorphology, climate, etc) for announcements including job advertisements, high-impact and high-relevance journal postings, obituaries, broad questions, call-for-papers, conference notifications, and other such community-relevant communications. CRYOLIST welcomes a diverse set of members at all scientific career stages including non-scientists, technicians, practitioners, and commercial enterprises. You can [sign up for CRYOLIST for free](https://lists.cryolist.org/mailman/listinfo/cryolist).
