# Absences and Makeup Policies

## Excused Absences {#sec-absences}

[University policy](https://policy.umn.edu/education/makeupwork) recognizes that there are a variety of legitimate circumstances in which students will miss coursework, and that accommodations for makeup work will be made. These situations generally fall into several categories:

-   illness, physical or mental, of the student or a student's dependent;
-   medical conditions related to pregnancy;
-   participation in intercollegiate athletic events;
-   subpoenas;
-   jury duty;
-   military service;
-   bereavement, including travel related to bereavement;
-   religious observances;
-   participation in formal University system governance, including the University Senate, Student Senate, and Board of Regents meetings, by students selected as representatives to those bodies;
-   taking college entrance exams (PSAT, ACT, SAT) for Post-Secondary Enrollment Option (PSEO) students that are provided at their high school; and
-   activities sponsored by the University if identified by the senior academic officer for the campus or the officer's designee as the basis for excused absences.

These absences should be pre-coordinated with the instructor as soon as they are known - in emergency or unexpected situation, communication may occur after the fact. **All other absences are considered unexcused absences**

## Unexcused Absences {#sec-unexcusedabsences}

*Assigned Paper Summary* If you do not complete an assigned paper summary worksheet due to an unexcused absence, you must turn it in **no later** than the following week to receive an assessment of satisfactory - any unexcused work turned in more than 1 week after the due date will be considered less than satisfactory.

*Group Jigsaw Worksheet* If you miss a class session due to an unexcused absence, you will either need to complete jigsaw worksheet on your own or in consultation with a partner from your group. You must turn it in **no later** than the following week to receive an assessment of satisfactory - any unexcused work turned in more than 1 week after the due date will be considered less than satisfactory.

*Synthesis Product* The synthesis product is due prior to the beginning of our final class session on Friday, December 6th. Any synthesis products not completed by that time must be turned in **no later** than December 13th to receive an assessment of satisfactory - any unexcused work turned in more than 1 week after the due date will be considered less than satisfactory.